/// <reference types="vitest" />
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { writeFileSync, mkdirSync } from 'fs'
import { resolve } from 'path'

/**
 * Vite plugin that generates `public/env-config.js` from VITE_ env vars.
 * Runs on both `dev` and `build` so the runtime config is always up to date.
 */
function envConfigPlugin() {
  const publicDir = resolve(__dirname, 'public')
  const outFile = resolve(publicDir, 'env-config.js')

  function generate() {
    try { mkdirSync(publicDir, { recursive: true }) } catch {}

    const clientId = process.env.VITE_GOOGLE_CLIENT_ID || ''
    const content = [
      '// Auto-generated by vite.config.js — do not edit manually.',
      'window.__NYAYA_CONFIG__ = window.__NYAYA_CONFIG__ || {};',
      `window.__NYAYA_CONFIG__.VITE_GOOGLE_CLIENT_ID = ${JSON.stringify(clientId)};`,
      '',
    ].join('\n')

    writeFileSync(outFile, content, 'utf-8')
  }

  return {
    name: 'generate-env-config',
    buildStart() { generate() },
    configureServer() { generate() },
  }
}

export default defineConfig({
  plugins: [envConfigPlugin(), react(), tailwindcss()],

  // ── Dev server ─────────────────────────────────────────────────────────
  server: {
    proxy: {
      '/chat': 'http://localhost:8000',
      '/mapping': 'http://localhost:8000',
      '/map': 'http://localhost:8000',
      '/ingest': 'http://localhost:8000',
      '/health': 'http://localhost:8000',
      '/auth': 'http://localhost:8000',
      '/extract': 'http://localhost:8000',
    },
  },

  // ── Production build optimizations ─────────────────────────────────────
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          // Split large vendor libraries into separate cacheable chunks.
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          'vendor-ui': ['framer-motion', 'lucide-react'],
        },
      },
    },
    // Generate source maps for error tracking in production.
    sourcemap: 'hidden',
  },

  // ── Testing ────────────────────────────────────────────────────────────
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/setupTests.js',
  },
})
