import type { ChatSource } from '../types';
import { toPlainText } from './text';

/** Page geometry, in millimetres (A4). */
const PAGE = { width: 210, height: 297, margin: 20 };
const CONTENT_WIDTH = PAGE.width - PAGE.margin * 2;

const INK = [16, 18, 29] as const;
const MUTED = [90, 96, 112] as const;
const GOLD = [166, 124, 45] as const;

function sourceLine(source: string | ChatSource): string {
  if (typeof source === 'string') return source;
  if (!source) return 'Unknown source';
  if (source.law_type === 'WEB') return `${source.section || 'Web source'} — ${source.url || ''}`;
  const page = source.page_number ? `, p. ${source.page_number}` : '';
  return `${source.law_type || 'Law'} section ${source.section || 'unknown'}${page}`;
}

export interface ExportAnswerOptions {
  question: string;
  answer: string;
  sources?: Array<string | ChatSource>;
}

/**
 * Write one question-and-answer to a PDF, citations included.
 *
 * People take legal answers to an advocate, print them, or file them with a
 * matter — so the export carries the provisions it relied on and the same
 * disclaimer shown in the interface, on every page. Without the citations a
 * saved answer is an unsourced assertion.
 *
 * jsPDF is imported dynamically: it is roughly a third of a megabyte and only
 * needed the moment somebody actually asks for a file.
 */
export async function exportAnswerToPdf({ question, answer, sources = [] }: ExportAnswerOptions) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const generated = new Date();
  let y = PAGE.margin;

  const footer = () => {
    const page = doc.getNumberOfPages();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(
      'Generated by NyayaAI. General information about Indian law — not legal advice.',
      PAGE.margin,
      PAGE.height - 12,
    );
    doc.text(String(page), PAGE.width - PAGE.margin, PAGE.height - 12, { align: 'right' });
  };

  const newPage = () => {
    footer();
    doc.addPage();
    y = PAGE.margin;
  };

  /** Reserve vertical space, starting a page when the block will not fit. */
  const reserve = (height: number) => {
    if (y + height > PAGE.height - 22) newPage();
  };

  const write = (
    text: string,
    {
      size = 10,
      style = 'normal',
      color = INK,
      leading = 1.45,
      gap = 0,
    }: {
      size?: number;
      style?: 'normal' | 'bold' | 'italic';
      color?: readonly [number, number, number];
      leading?: number;
      gap?: number;
    } = {},
  ) => {
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lineHeight = (size * leading) / 2.835; // pt → mm
    for (const line of doc.splitTextToSize(text, CONTENT_WIDTH) as string[]) {
      reserve(lineHeight);
      doc.text(line, PAGE.margin, y);
      y += lineHeight;
    }
    y += gap;
  };

  const rule = (gap = 4) => {
    reserve(gap + 2);
    doc.setDrawColor(214, 218, 226);
    doc.setLineWidth(0.2);
    doc.line(PAGE.margin, y, PAGE.width - PAGE.margin, y);
    y += gap;
  };

  /* Masthead */
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(...INK);
  doc.text('NyayaAI', PAGE.margin, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(
    generated.toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }),
    PAGE.width - PAGE.margin,
    y,
    { align: 'right' },
  );
  y += 4;
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.line(PAGE.margin, y, PAGE.margin + 22, y);
  y += 9;

  write('QUESTION', { size: 7.5, style: 'bold', color: MUTED, gap: 1.5 });
  write(toPlainText(question) || '—', { size: 11, style: 'bold', gap: 5 });

  rule(6);

  write('ANSWER', { size: 7.5, style: 'bold', color: MUTED, gap: 1.5 });
  for (const paragraph of toPlainText(answer).split(/\n{2,}/)) {
    if (paragraph.trim()) write(paragraph.trim(), { size: 10, gap: 3.2 });
  }

  if (sources.length > 0) {
    y += 2;
    rule(6);
    write(`SOURCES (${sources.length})`, { size: 7.5, style: 'bold', color: MUTED, gap: 1.5 });
    sources.forEach((source, index) => {
      write(`${index + 1}. ${sourceLine(source)}`, { size: 9, color: MUTED, gap: 1.2 });
    });
  }

  footer();

  const stamp = generated.toISOString().slice(0, 10);
  const slug =
    toPlainText(question)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 48) || 'answer';

  doc.save(`nyayaai-${slug}-${stamp}.pdf`);
}
